### ISSUE TITLE
Implement product-config for Hive operator

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/hive-operator#1]
Currently the Hive operator works with hard coded configs instead of using a properly parsed product-config generated files.

Definition of done:

- [x] A productconfig json file has been created for the most common config options needed to get Hive up and running
- [x] The options from the json file are exposed in the CRD
- [x] The productconfig framework is used to validate and generate the ConfigMaps

**Comment by fhennig** [comment]
Some info I gathered:
- We only have one role for now: "metastore"
- The metastore admin manual for our version (2.3.9) can be found [here](https://cwiki.apache.org/confluence/display/Hive/AdminManual+Metastore+Administration) and it documents the relevant configuration properties.
- configuration is done in the `hive-site.xml` file, which also uses the common "hadoop-style" xml config schema
- Before the metastore service can be started, the database schema needs to be initialized with [this command](https://cwiki.apache.org/confluence/display/hive/gettingstarted#GettingStarted-RunningHiveServer2andBeeline.1):
      `$ $HIVE_HOME/bin/schematool -dbType <db type> -initSchema`
- Hive requires `HADOOP_HOME` to be set or for hadoop to be in the `$PATH`. The metastore doesn't actually run hadoop, but seems to require hadoop as a library. From what I found online, the schematool also seems to require libraries from hadoop. This is also the case for the Hive 3 "standalone" Metastore (which doesn't require a full Hive install, but *still* requires a hadoop install).
- The startup command is `bin/hive --service metastore`

**Comment by fhennig** [comment]
For the schema initialization, we can just validate the schema like so:
    ./hive --config {{configroot}}/conf --service schemaTool -dbType <dbType> -validate
=> returncode 0 on success, 1 otherwise.

and then, if it is not initialized, we can do that like so:
    ./hive --config {{configroot}}/conf --service schemaTool -dbType <dbType> -initSchema

We need the dbType for that, so that should be in the hivecluster crd
