### ISSUE TITLE
Move Database config to a secret

### ISSUE THREAD

**Issue by fhennig** [stackabletech/hive-operator#148]
As a user I'd like to be able to configure the database credentials using secrets

This is done when
- [ ] connection credentials are not part of the CR anymore but instead are split out to a secret
- [ ] integration tests, examples and documentation have been updated

**Comment by fhennig** [comment]
> s3 secret reference into a complex enum and think about other storage solutions

I think I just copied this from the Google doc when I made the ticket.

I think what is mean here is that you can just have a key `backendStorage` and then multiple options, this can be implemented with different enum variants. But not for now.

**Comment by lfrancke** [comment]
When refining this please note that it might end up as a bigger task (i.e. other operators might have the same issue and we might want an ADR / consistent CRD).
As such it could be that this ticket needs to be changed to a research task but I'm not entirely sure so I'll leave it like this for now.

**Comment by sbernauer** [comment]
Just wanted to mention, that the acceptance criteria of this ticket as well as the description originally *meant* to only fix the bug we currently have. This should be rather easy and doable in less than a day.
We have a ticket for a generic reusable struct: https://github.com/stackabletech/issues/issues/238
It was my fault to not link that in July of this year during creation...

**Comment by maxgruber19** [comment]
@lfrancke @sbernauer any updates on this stream? My heart hurts everytime I stumble over HiveCluster resources with passwords clearly visible which makes them unstorable in version control systems :disappointed_relieved:

**Comment by lfrancke** [comment]
Sorry for the missing updates.
We want to mend your broken heart 💔 and have this scheduled for the next release. 

This is a mistake from our very early days. We have much stricter controls over CRD changes these days. 

We have debated whether to do the "big solution" and move all DB connections to a common structure.... But that might not happen for the next release.

**Comment by dougb** [comment]
Hi, Possible customer here currently evaluating SDP. I just discovered this issue trying to setup HMS.
This must be resolved for us to use it in production.
Glad to hear that it will be fixed in the next release. 

@soenkeliebau for viz.

**Comment by adwk67** [comment]
We discussed this last week and agreed to do a simple fix to begin with, and to cover generic connections (following https://docs.stackable.tech/home/stable/contributor/adr/adr029-database-connection) at a later date.

**Comment by fhennig** [comment]
@adwk67 Was there documentation added for this? I don't think I see anything in nightly

**Comment by adwk67** [comment]
Nothing was *added* specifically, no, but existing usage/examples were updated.

**Comment by fhennig** [comment]
Alright :+1: thanks
