### ISSUE TITLE
Error, when using postgres as Database for the hive-metastore

### ISSUE THREAD

**Issue by semmjon** [stackabletech/hive-operator#167]
### Affected version

0.5.0

### Current and expected behavior

I would like to use a Postgres instead of Derby for the database.
For the example I set up a database with the bitnami helm chart (https://bitnami.com/stack/postgresql/helm).
The hive configuration looks like this:
```yaml
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-derby
  namespace: bi-stack
spec:
  version: 2.3.9
  metastore:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          metricsPort: 11111
          database:
            connString: jdbc:postgresql://hive-postgresql.bi-stack.svc.cluster.local:5432/hive
            user: hive-user
            password: hive-password
            dbType: postgres
          s3Connection:
            endPoint: "#####"
            accessKey: "#####"
            secretKey: "#####"
            sslEnabled: true
            pathStyleAccess: true
```

### Possible solution

Update of the hive source libraries / driver, becouse of 
```Underlying cause: org.postgresql.util.PSQLException : The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.```

### Error-Log
```
SLF4J: Found binding in [jar:file:/stackable/apache-hive-2.3.9-bin/apache-hive-2.3.9-bin/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/stackable/apache-hive-2.3.9-bin/hadoop-2.10.1/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Starting metastore validation

org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version.
Underlying cause: org.postgresql.util.PSQLException : The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
SQL Error code: 0
Use --verbose for detailed stacktrace.
*** schemaTool failed ***
No valid schema found, initializing schema ...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/stackable/apache-hive-2.3.9-bin/apache-hive-2.3.9-bin/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/stackable/apache-hive-2.3.9-bin/hadoop-2.10.1/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Metastore connection URL:	 jdbc:postgresql://hive-postgresql.bi-stack.svc.cluster.local:5432/hive
Metastore Connection Driver :	 org.postgresql.Driver
Metastore connection User:	 hive
org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version.
Underlying cause: org.postgresql.util.PSQLException : The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
SQL Error code: 0
Use --verbose for detailed stacktrace.
```

### Environment

helm install hive-operator stackable-devel/hive-operator
helm install hive-postgresql -n postgres bitnami/postgresql     --set auth.username=hive-user \
    --set auth.password=hive-password     --set auth.database=hive

**Comment by maltesander** [comment]
As a quick fix can you try:
```
helm install hive bitnami/postgresql --version=10 \
    --set postgresqlUsername=hive \
    --set postgresqlPassword=hive \
    --set postgresqlDatabase=hive
```
and
```
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-postgres
  namespace: bi-stack
spec:
  version: 2.3.9
  metastore:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          database:
            connString: jdbc:postgresql://hive-postgresql.bi-stack.svc.cluster.local:5432/hive
            user: hive
            password: hive
            dbType: postgres
          s3Connection:
            endPoint: "#####"
            accessKey: "#####"
            secretKey: "#####"
            sslEnabled: true
            pathStyleAccess: true
```
As you said, currently our libraries do not work with postgres version > 10.

**Comment by semmjon** [comment]
Thanks, that works!
Can you roughly estimate when new versions will also be compatible?

**Comment by maltesander** [comment]
Not right now, currently were focusing on a new release. @lfrancke do you have an opinion / estimation on that?

**Comment by maltesander** [comment]
We did some research. Hive 2.3.9 up to 3.1.3 uses JDBC client `postgresql-9.4.1208.jre7` which does not support SCRAM (https://wiki.postgresql.org/wiki/List_of_drivers#Drivers). SCRAM is the default from postgres version 14 (some bitnami images may have activated it earlier). Make sure to use a postgres version using MD5 in order to work with the current hive releases.

**Comment by semmjon** [comment]
Thanks for the information.  I have understood that so far and i will see if and how I can activate MD5.  However, it could be problematic since we want to use a DaaS for production (where we can probably configure less).  Alternatively, I can also help you by sending you an example Dockerfile where it works with a hive-metastore-standalone.

**Comment by lfrancke** [comment]
Thank you. I assume you're just adding a recent JDBC driver to the Docker image?
The standalone metastore doesn't ship with any drivers out of the box.

We've tried to stay away from changing upstream projects as much as possible.

**Comment by soenkeliebau** [comment]
We have updated the docs with a comment regarding this constraint: https://docs.stackable.tech/hive/usage.html

**Comment by razvan** [comment]
Seems to be done.
