### ISSUE TITLE
Test Hive 2.3.9 with newer PostgreSQL JDBC driver JAR

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/hive-operator#170]
Hive (up until the latest released version 3.1.3) ships with an old version of the PostgreSQL driver (9.x) which does not support SCRAM authentication which is the default as of PostgreSQL 14 (and can be used as of PostgreSQL 10).

It seems possible for us to just replace the PostgreSQL JDBC JAR with a newer version. This would need to be integrated into our Docker image build.

This ticket is only to TEST whether Hive still works when we use the latest available driver.
It is done when a simple test has been performed (e.g. start hive metastore, create a hive table, delete a hive table etc.) against Hive 2.3.9 and 3.1.3 with the postgres jar file replaced with the latest available one.

We can then decide on follow-up issues if needed.

Hive 4 will ship with a newer driver but there is no release date as of yet.

**Comment by razvan** [comment]
This issue came back with a vengence now that Bitnami has retired old Helm charts for Postgresql. SCRAM is now the default.
