### ISSUE TITLE
Properly support S3 structs

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/hive-operator#193]
When implementing support for S3 in the operators out there we took some shortcuts like ignoring `accessStyle` and `tls` settings for now. We need to honor them and not just silently ignore them.

What needs to be done is described in https://github.com/stackabletech/issues/issues/226

**Comment by fhennig** [comment]
I want to add to this ticket that there should also be proper documentation for S3 support. What we have now: https://docs.stackable.tech/hive/stable/usage.html#_s3_support isn't helpful at all
