### ISSUE TITLE
Nit: Link to docs in readme are broken

### ISSUE THREAD

**Issue by timrobertson100** [stackabletech/hive-operator#241]
https://docs.stackable.tech/hive/index.html is a dead link

**Comment by lfrancke** [comment]
@fhennig I'm afraid this is more fallout from your URL change?

**Comment by fhennig** [comment]
This is from when we versioned the docs for the operators, so probably since a few weeks already

**Comment by fhennig** [comment]
The correct link is: https://docs.stackable.tech/hive/stable/index.html

To fix this, the link needs to be replaced

**Comment by lfrancke** [comment]
Thank you for the report @timrobertson100
