### ISSUE TITLE
Enable Log Aggregation for Hive

### ISSUE THREAD

**Issue by maltesander** [stackabletech/hive-operator#290]
See https://github.com/stackabletech/hbase-operator/issues/291 and https://github.com/stackabletech/docker-images/pull/283 for reference.

This is part of https://github.com/stackabletech/issues/issues/288

Blocked by: 
- [x] https://github.com/stackabletech/docker-images/pull/293
- [x] https://github.com/stackabletech/operator-rs/pull/540

**Comment by lfrancke** [comment]
This did _not_ make it into 23.1, correct?
