### ISSUE TITLE
High availability for Hive Metastore

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/hive-operator#380]
Provide a means to deploy multiple Hive metastores in a high availability configuration. There should be a single endpoint that other components connect to that route to one of the available metastores.

**Comment by sbernauer** [comment]
I think you just need to deploy multiple replicas and there you go, see e.g. trino smoke test https://github.com/stackabletech/trino-operator/blob/4003e62dede175eb816d57836fdf6ea6ea7e0960/tests/templates/kuttl/smoke/08-install-hive.yaml.j2#L28 and https://github.com/stackabletech/trino-operator/blob/4003e62dede175eb816d57836fdf6ea6ea7e0960/tests/templates/kuttl/smoke/10-install-trino.yaml.j2#L70
(Obviously don't use derby for HMS)

**Comment by Jimvin** [comment]
The docs suggest that HA is not supported -  https://docs.stackable.tech/home/23.1/hive/discovery. We should clarify if multiple instances are supported and whether the dependant services can use the discovery configMap to connect to Hive as a high availability service.
