### ISSUE TITLE
Kerberos authentication for Hive metastore

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/hive-operator#387]
The operator should support kerberos authentication to be enabled on the Hive metastore. Hive metastore support Kerberos for authentication is required if Hive metastore is to access a kerberised HDFS cluster. There isn't a way at this time to enable Hive metastore as a Kerberised HDFS client without enabling Kerberos authentication for metastore itself. Authentication is also  prerequisite for enabling authorisation.

**Comment by adwk67** [comment]
Closed by mistake
