### ISSUE TITLE
Document driver installation for Hive metastore backend database

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/hive-operator#416]
Certain databases (Oracle, MySQL) do not allow shipping their database driver, and so as a user of that database with Hive, I have to manually provide the driver to Hive. As a user, I want to find instructions in the Stackable documentation on how to install and configure such a driver with a Stackable-deployed Hive instance, so I can use Hive with my proprietary database.

## Suggested steps to document

- instruct user to deploy a PV (ReadOnlyMany mode)
- explain how to copy stuff into the PV
- mount the PV on the Pods with podOverrides
- set the aux jar path: https://chetnachaudhari.github.io/2016-02-16/how-to-add-auxiliary-jars-in-hive/ with configOverrides

Also: we should update the "required external components" page to note that some drivers have to be installed manually.

### Considered alternatives

- building a custom image (quite a bit of overhead, also requires a registry/way to deploy the image)
- copy the driver from s3 or another place to curl from

## Tasks

```[tasklist]
### Tasks
- [x] Write the tutorial/guide (and test it while writing)
- [x] Mention the guide in the "Required external components" page
```

## Open Questions

- Should we have an integration test for this? Should it be somehow entirely coded so we can test if it keeps working? 

## Acceptance criteria

- The "Usage guide" for the Hive operator contains a document that explains how to install custom drivers
- The guide is mentioned in relevant places to make it easy to find for users

**Comment by lfrancke** [comment]
Refinement by Malte, Felix

**Comment by fhennig** [comment]
## Refinement notes

- Why can't we ship the drivers by default? 

Do users have to build custom images? Or just mount it in? 

From the hive docs:

> If you are using MySQL as the datastore for metadata, put MySQL jdbc libraries in HIVE_HOME/lib before starting Hive Client or HiveMetastore Server.

we should also update the "required external components" page

**Comment by lfrancke** [comment]
We can't ship certain drivers for licensing reasons. So we'll need a documented way to include new ones either way.

**Comment by soenkeliebau** [comment]
looks good to me, just to double check, are the "considered alternatives" planned to include as an "honorable mention" in the docs?

**Comment by fhennig** [comment]
I think they weren't, but good idea!

**Comment by adwk67** [comment]
Another alternative might be to use git-sync in "one-off" mode to download external resources.

**Comment by lfrancke** [comment]
Could you please add a link to the documentation? (can be nightly)
